### ISSUE TITLE
Some major updates are not caught by `Y.0.0` mask

### ISSUE THREAD

**Issue by Hypnosphi** [dependencies-io/actor-repo-issue#5]
Sometimes there is actually no `1.0.0` version published, only `1.0.1` and higher:
```
Finding available versions for chroma-js
npm info it worked if it ends with ok
npm info using npm@5.5.1
npm info using node@v8.7.0
npm info attempt registry request try #1 at 23:52:08
npm http request GET https://registry.npmjs.org/chroma-js
npm http 200 https://registry.npmjs.org/chroma-js
[
  "0.2.5",
  "0.4.3",
  "0.4.7",
  "0.4.8",
  "0.4.10",
  "0.4.11",
  "0.5.1",
  "0.5.2",
  "0.5.4",
  "0.5.5",
  "0.5.6",
  "0.5.7",
  "0.5.8",
  "0.5.9",
  "0.6.0",
  "0.6.1",
  "0.6.2",
  "0.6.3",
  "0.7.1",
  "0.7.2",
  "0.7.3",
  "0.7.4",
  "0.7.5",
  "0.7.6",
  "0.7.8",
  "1.0.1",
  "1.1.0",
  "1.1.1",
  "1.2.1",
  "1.2.2",
  "1.3.0",
  "1.3.1",
  "1.3.2",
  "1.3.3",
  "1.3.4"
]
npm info ok 
```

So looks like we need something other than `Y.0.0` for detecting major updates

**Comment by davegaeddert** [comment]
Thanks @Hypnosphi. I know we talked about that issue when designing those masks, but chose not to deal with that particular use-case right away. @paulortman can you remember what some of the ideas were to deal with this?

**Comment by paulortman** [comment]
@davegaeddert I made [an issue](https://github.com/dropseed/version-filter/issues/15) in the version filter lib to record my thoughts...

**Comment by davegaeddert** [comment]
Thanks. I'll close this issue so we can track it over there.
